[project]
name = "mcp-local-clients"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.9.2",
    "nest-asyncio>=1.6.0",
    "ollama>=0.5.1",
    "rich>=14.0.0",
]
